Added god.html (Fernando Alonso)
DishpitDev/Slopify pull request #195
Opened 2024-12-30 17:53 UTC by CarlosOlivaAznar

2024-12-30 19:05 UTC, Dishpit requested changes
merge conflicts, pls fix

2024-12-31 14:25 UTC, Dishpit requested changes

2024-12-31 14:25 UTC, Dishpit commented on static/video/fernandoAlonso.mp4
last thing, can we get this file size condensed by a lot pls? <3

2024-12-31 15:26 UTC, merged

2024-12-31 15:31 UTC, CarlosOlivaAznar commented on static/video/fernandoAlonso.mp4
Okay np