Wednesdayify wednesdays, my dudes.
DishpitDev/Slopify pull request #224
Opened 2024-12-30 23:59 UTC by garrett-is-a-swann

didn't test - I'm not running this repo on my computer sorry lmao

2024-12-31 00:22 UTC, ItsNyoty commented
Try testing

2024-12-31 07:03 UTC, garrett-is-a-swann commented
The code works. Just don't know how files are served, but I copied 8ball's method of include so should work fine.

2024-12-31 14:46 UTC, Dishpit requested changes
merge conflicts, pls fix <3

2025-01-03 17:46 UTC, Dishpit commented
superseded by #307

2025-01-03 17:46 UTC, closed without merging