🤖 MAJOR FEATURE: SlopBot 🤖
DishpitDev/Slopify pull request #228
Opened 2024-12-31 00:51 UTC by zoogies

<h3>🤖 SlopBot: On device infinite slop delivery 🤖</h3>
<p>Implemented Edge Compute LLM Inference through WebGPU and web-llm. WebGPU is not available on every platform and browser, but there is a handled error if that occurs</p>
<h4>Preview of Changes</h4>

Feature | Screenshot
-- | --
Main Website Integration | ![image](https://github.com/user-attachments/assets/63e668fc-d885-4d13-94da-a193d522fc30)
Model Selection on Slopbot | ![image](https://github.com/user-attachments/assets/67b0c5ee-7a11-4f96-8701-cd894afffaa0)
Initialization Process | ![image](https://github.com/user-attachments/assets/8a53d313-3589-4076-9c7a-cabcc16f3919)
Handled WebGPU Error | ![image](https://github.com/user-attachments/assets/97b1f975-8aef-4808-a08c-ee25faa4e3ad)
Successful Slop Generation | ![image](https://github.com/user-attachments/assets/aaee560d-4fd0-4fc8-a102-381326148e00)
Slop Previewer | ![image](https://github.com/user-attachments/assets/79fa736d-110c-4084-bdbd-3931a9719d91)

<h1>Infinite slop, for free?!?!</h1>

![Gf8ZROUW4AApzuu](https://github.com/user-attachments/assets/2a8eb317-0130-492b-a255-10dc488ca524)

2024-12-31 14:47 UTC, Dishpit requested changes
merge conflicts, pls fix <3

2024-12-31 17:13 UTC, zoogies commented
Resolved, and updated to follow new formats (separate stylesheet)

Tested on my m1 mbp, with high tps!!

<img width="898" alt="image" src="https://github.com/user-attachments/assets/616cdccc-b71c-42fd-8edb-ae1c2ddec23c" />

2024-12-31 17:14 UTC, zoogies commented
@Dishpit please give this a go yourself before merging, just to make sure all is well

2024-12-31 21:37 UTC, Dishpit commented
it has more merge conflicts :(

2024-12-31 23:05 UTC, zoogies commented
Stop changing `index.html`!!!!!!!!!!!!!!! (I will fix now 😄)

2025-01-01 00:15 UTC, Dishpit requested changes
you guessed it

more merge conflicts

2025-01-01 00:26 UTC, zoogies commented
@Dishpit fixed, again

2025-01-01 00:27 UTC, merged

2025-01-01 00:29 UTC, zoogies commented
![262f7dd34725ca5c7760d1dfba155736](https://github.com/user-attachments/assets/a4c4a910-08cd-4808-893e-42a79901b8c0)